config/routes.rb
Rails.application.routes.draw do
  get "index/home"
  get "index/resources"
  resources :worksheets
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root 'index#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/education.rb
class Education < ApplicationRecord
  EDUCATION_STATUS = {
    none: "n/a",
    complete: "Complete",
    selected_resident: "Selected (resident)",
    selected_non_resident: "Selected (non-resident)",
  }

  belongs_to :worksheet

  enum ews: { none: 0, complete: 1, selected_resident: 2, selected_non_resident: 3 }, _prefix: true
  enum cns: { none: 0, complete: 1, selected_resident: 2, selected_non_resident: 3 }, _prefix: true
  enum war_college: { none: 0, complete: 1, selected_resident: 2, selected_non_resident: 3 }, _prefix: true
  enum graduate_degree: { none: 0, complete: 1, selected_resident: 2, selected_non_resident: 3 }, _prefix: true
  enum self_study: { none: 0, complete: 1, selected_resident: 2, selected_non_resident: 3 }, _prefix: true
  enum jpm_phase_i: { none: 0, complete: 1, selected_resident: 2, selected_non_resident: 3 }, _prefix: true
  enum jpm_phase_ii: { none: 0, complete: 1, selected_resident: 2, selected_non_resident: 3 }, _prefix: true
  enum other: { none: 0, complete: 1, selected_resident: 2, selected_non_resident: 3 }, _prefix: true
end

app/models/worksheet.rb
class Worksheet < ApplicationRecord
  COMPONANTS = ["Active", "Reserve"]

  OFFICER_RANKS = [
    "Warrant Officer",
    "Chief Warrant Officer 2",
    "Chief Warrant Officer 3",
    "Chief Warrant Officer 4",
    "Chief Warrant Officer 5",
    "Second Lieutenant",
    "First Lieutenant",
    "Captain",
    "Major",
    "Lieutenant Colonel",
    "Colonel"
  ]

  REPORTING_OCCASIONS = [
    "Annual (AN)",
    "Change of Duty (CHOD)",
    "Direct (DIR)",
    "Disability Retirement (DISAB)",
    "End of Tour (EOT)",
    "Promotion (PROMO)",
    "Reenlistment Confirmation (RFC)",
    "Reenlistment Confirmation (Mobile) (RFC-M)",
    "Special (SPE)",
    "Temporary Duty (TEMDU)",
    "Transfer (TRANS)",
    "Non-Selection for Promotion (NSP)"
  ]

  USMCR_STATUSES = [
    "Inactive Reserve (IRR)",
    "Individual Mobilization Augmentee (IMA)",
    "Individual Ready Reserve (IRR)",
    "Mobilized",
    "Mobilization Day (M-Day)",
    "Permanent Disability Retired List (PDRL)",
    "Ready Reserve",
    "Retired Reserve",
    "Selected Marine Corps Reserve (SMCR)",
    "Standby Reserve",
    "Temporary Disability Retired List (TDRL)"
  ]

  has_one :education, dependent: :destroy
  accepts_nested_attributes_for :education

  validates :mro_rank,
            :rs_rank,
            :ro_rank, presence: true, inclusion: { in: OFFICER_RANKS }

  validates :from_date,
            :to_date,
            :mmsb_due_date,
            presence: true

  validates :mro_component, presence: true, inclusion: { in: COMPONANTS }
  validates :mro_status, presence: true, inclusion: { in: USMCR_STATUSES }
  validates :reporting_occasion, presence: true, inclusion: { in: REPORTING_OCCASIONS }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def home
  end

  def resources
  end
end

app/controllers/worksheets_controller.rb
class WorksheetsController < ApplicationController
  before_action :set_worksheet,only: %i[ show edit update destroy ]

  # GET /worksheets or /worksheets.json
  def index
    @worksheets = Worksheet.all
  end

  # GET /worksheets/1 or /worksheets/1.json
  def show
  end

  # GET /worksheets/new
  def new
    @worksheet = Worksheet.new
    @worksheet.build_education
  end

  # GET /worksheets/1/edit
  def edit
  end

  # POST /worksheets or /worksheets.json
  def create
    @worksheet = Worksheet.new(worksheet_params)

    respond_to do |format|
      if @worksheet.save
        format.html { redirect_to @worksheet,notice: "Worksheet was successfully created." }
        format.json { render :show,status: :created,location: @worksheet }
      else
        format.html { render :new,status: :unprocessable_entity }
        format.json { render json: @worksheet.errors,status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /worksheets/1 or /worksheets/1.json
  def update
    respond_to do |format|
      if @worksheet.update(worksheet_params)
        format.html { redirect_to @worksheet,notice: "Worksheet was successfully updated." }
        format.json { render :show,status: :ok,location: @worksheet }
      else
        format.html { render :edit,status: :unprocessable_entity }
        format.json { render json: @worksheet.errors,status: :unprocessable_entity }
      end
    end
  end

  # DELETE /worksheets/1 or /worksheets/1.json
  def destroy
    @worksheet.destroy!

    respond_to do |format|
      format.html { redirect_to worksheets_path,status: :see_other,notice: "Worksheet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_worksheet
      @worksheet = Worksheet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def worksheet_params
      params.require(:worksheet).permit(
        :mro_rank,
        :mro_name,
        :mro_billet,
        :mro_unit,
        :mro_component,
        :mro_status,
        :reporting_occasion,
        :mmsb_due_date,
        :from_date,
        :to_date,
        :rs_rank,
        :rs_name,
        :rs_billet,
        :ro_rank,
        :ro_name,
        :ro_billet,
        :commendatory,
        :commendatory_description,
        :recommended_comments,
        :amplifying_information,
        :recommended_comparative_assessment,
        education_attributes: [
          :ews,
          :cns,
          :war_college,
          :graduate_degree,
          :self_study,
          :jpm_phase_i,
          :jpm_phase_ii,
          :other,
          :other_school_name
        ]
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/worksheets_helper.rb
module WorksheetsHelper
end

app/views/index/home.html.erb
<div class="container text-center mt-5">
  <h1>MROW</h1>

  <div class="image-container mt-4">
    <%= image_tag("BW-EGA.png", alt: "Eagle, Globe, and Anchor") %>
  </div>

  <%= link_to "Create New MROW", new_worksheet_path, class: "btn btn-primary btn-dark mt-5" %>
</div>

app/views/index/resources.html.erb
  <object data="/pdfs/pes_manual.pdf" type="application/pdf" width="100%" height="1000px">
    <p>Your browser does not support PDFs. Please <a href="/pdfs/pes_manual.pdf">download the PDF</a>.</p>
  </object>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || 'Mrow' %></title>
    <meta name='viewport' content='width=device-width,initial-scale=1'>
    <meta name='apple-mobile-web-app-capable' content='yes'>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel='manifest' href='/manifest.json'>
    <link rel='icon' href='/icon.png' type='image/png'>
    <link rel='icon' href='/icon.svg' type='image/svg+xml'>
    <link rel='apple-touch-icon' href='/icon.png'>
    <%= stylesheet_link_tag 'application', 'data-turbo-track': 'reload' %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.jsdelivr.net/npm/@easepick/bundle@1.2.1/dist/index.umd.min.js"></script>
  </head>

  <body>
    <%= render 'partials/header' %>
    <%= yield %>

    <script>
      document.addEventListener('DOMContentLoaded', function() {
        const datepickers = document.querySelectorAll('.datepicker');

        datepickers.forEach((datepicker) => {
          new easepick.create({
            element: datepicker,
            css: [
              'https://cdn.jsdelivr.net/npm/@easepick/bundle@1.2.1/dist/index.css'
            ]
          });
        });
      });
    </script>
  </body>
</html>

app/views/partials/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", index_home_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "PES Manual", index_resources_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Worksheets", worksheets_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "New Worksheet", new_worksheet_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/worksheets/_education.html.erb
<div class="container mt-4">
  <h3>Education and Experience</h3>

  <div class="row mt-5">
    <div class="col-md-4">
      <%= form.fields_for :education do |education_form| %>
        <div class="form-group">
          <%= education_form.label :ews, 'Career-Level School (EWS)' %>
          <%= education_form.select :ews, 
            options_for_select(
              Education::EDUCATION_STATUS.map { |k, v| [v, k] }
            ), 
            input_html: { class: "form-control" } 
          %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/worksheets/_form.html.erb
<%= simple_form_for worksheet, html: { class: "needs-validation", novalidate: true } do |form| %>
  <% if worksheet.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(worksheet.errors.count, "error") %> prohibited this worksheet from being saved:</h4>
      <ul>
        <% worksheet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container mt-4">
    <h3>Marine Reported On (MRO)</h3>
    
    <div class="row mt-3">
      <div class="col-md-3">
        <%= form.input :mro_rank,
          as: :select,
          collection: Worksheet::OFFICER_RANKS,
          label: "Rank",
          input_html: { class: "form-control" },
          include_blank: false,
          required: false %>
      </div>

      <div class="col-md-5">
        <%= form.input :mro_name, label: "Name (Last Name, First Name, Middle Initial)", input_html: { class: "form-control" } %>
      </div>

      <div class="col-md-4">
        <%= form.input :mro_billet, label: "Billet", input_html: { class: "form-control" } %>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-md-2">
        <%= form.input :mro_unit, label: "Unit", input_html: { class: "form-control" } %>
      </div>

      <div class="col-md-2">
        <%= form.input :mro_component,
          as: :select,
          collection: Worksheet::COMPONANTS,
          label: "Component",
          input_html: { class: "form-control" },
          include_blank: false,
          required: false %>
      </div>

      <div class="col-md-4">
        <%= form.input :mro_status,
          as: :select,
          collection: Worksheet::USMCR_STATUSES,
          label: "Status", input_html: { class: "form-control" },
          include_blank: false,
          required: false %>
      </div>

      <div class="col-md-4">
        <%= form.input :reporting_occasion,
          label: "Reporting Occasion",
          as: :select,
          collection: Worksheet::REPORTING_OCCASIONS,
          input_html: { class: "form-control" },
          include_blank: false,
          required: false %>
      </div>

      <div class="col-md-4 mt-3">
        <%= form.input :from_date, label: "From Date", as: :string, input_html: {class: "form-control datepicker" } %>
      </div>

      <div class="col-md-4 mt-3">
        <%= form.input :to_date, label: "To Date", as: :string, input_html: {class: "form-control datepicker" } %>
      </div>

      <div class="col-md-4 mt-3">
        <%= form.input :mmsb_due_date, label: "MMSB Due Date", as: :string, input_html: {class: "form-control datepicker"} %>
      </div>
    </div>

    <div class="row mt-3">
      <h3>Reporting Senior (RS)</h3>
      <div class="col-md-3">
        <%= form.input :rs_rank,
          as: :select,
          collection: Worksheet::OFFICER_RANKS,
          label: "Rank",
          input_html: { class: "form-control" },
          include_blank: false,
          required: false %>
      </div>
      <div class="col-md-5">
        <%= form.input :rs_name, label: "Name", input_html: { class: "form-control" } %>
      </div>
      <div class="col-md-4">
        <%= form.input :rs_billet, label: "Billet", input_html: { class: "form-control" } %>
      </div>
    </div>

    <div class="row mt-3">
      <h3>Reviewing Officer (RO)</h3>
      <div class="col-md-3">
        <%= form.input :ro_rank,
          as: :select,
          collection: Worksheet::OFFICER_RANKS,
          label: "Rank",
          input_html: { class: "form-control" },
          include_blank: false,
          required: false %>
      </div>
      <div class="col-md-5">
        <%= form.input :ro_name, label: "Name", input_html: { class: "form-control" } %>
      </div>
      <div class="col-md-4">
        <%= form.input :ro_billet, label: "Billet", input_html: { class: "form-control" } %>
      </div>
    </div>

    <%= render 'education', form: form %>

    <h3 class="mt-5">Recommendations</h3>

    <div class="mt-3">
      <%= form.input :commendatory, label: "This is a commendatory Fitness Report", as: :boolean, input_html: { class: "form-check-input checkbox-spacing" } %>
    </div>

    <div class="mt-3">
      <%= form.input :commendatory_description, label: "Commendatory Description", as: :text, input_html: { class: "form-control", rows: 3 } %>
    </div>

    <div class="mt-3">
      <%= form.input :recommended_comments, label: "Recommended Comments", as: :text, input_html: { class: "form-control", rows: 3 } %>
    </div>

    <div class="mt-3">
      <%= form.input :amplifying_information, label: "Amplifying Information", as: :text, input_html: { class: "form-control", rows: 3 } %>
    </div>

    <div class="mt-3">
      <%= form.input :recommended_comparative_assessment, label: "Recommended Comparative Assessment", input_html: { class: "form-control" } %>
    </div>

    <div class="form-group text-center mt-5">
      <%= form.submit "Submit", class: "btn btn-primary btn-dark" %>
    </div>
    <div class="mt-5"></div>
  </div>
<% end %>

app/views/worksheets/_worksheet.html.erb
<div id="<%= dom_id worksheet %>">
  <p>
    <strong>Mro rank:</strong>
    <%= worksheet.mro_rank %>
  </p>

  <p>
    <strong>Mro name:</strong>
    <%= worksheet.mro_name %>
  </p>

  <p>
    <strong>Mro billet:</strong>
    <%= worksheet.mro_billet %>
  </p>

  <p>
    <strong>Mro unit:</strong>
    <%= worksheet.mro_unit %>
  </p>

  <p>
    <strong>Mro component:</strong>
    <%= worksheet.mro_component %>
  </p>

  <p>
    <strong>Mro status:</strong>
    <%= worksheet.mro_status %>
  </p>

  <p>
    <strong>Reporting occasion:</strong>
    <%= worksheet.reporting_occasion %>
  </p>

  <p>
    <strong>Mmsb due date:</strong>
    <%= worksheet.mmsb_due_date %>
  </p>

  <p>
    <strong>From date:</strong>
    <%= worksheet.from_date %>
  </p>

  <p>
    <strong>To date:</strong>
    <%= worksheet.to_date %>
  </p>

  <p>
    <strong>Rs rank:</strong>
    <%= worksheet.rs_rank %>
  </p>

  <p>
    <strong>Rs name:</strong>
    <%= worksheet.rs_name %>
  </p>

  <p>
    <strong>Rs billet:</strong>
    <%= worksheet.rs_billet %>
  </p>

  <p>
    <strong>Ro rank:</strong>
    <%= worksheet.ro_rank %>
  </p>

  <p>
    <strong>Ro name:</strong>
    <%= worksheet.ro_name %>
  </p>

  <p>
    <strong>Ro billet:</strong>
    <%= worksheet.ro_billet %>
  </p>

  <p>
    <strong>Commendatory:</strong>
    <%= worksheet.commendatory %>
  </p>

  <p>
    <strong>Commendatory description:</strong>
    <%= worksheet.commendatory_description %>
  </p>

  <p>
    <strong>Recommended comments:</strong>
    <%= worksheet.recommended_comments %>
  </p>

  <p>
    <strong>Amplifying information:</strong>
    <%= worksheet.amplifying_information %>
  </p>

  <p>
    <strong>Recommended comparative assessment:</strong>
    <%= worksheet.recommended_comparative_assessment %>
  </p>

</div>

app/views/worksheets/edit.html.erb
<% content_for :title, "Editing worksheet" %>

<h1>Editing worksheet</h1>

<%= render "form", worksheet: @worksheet %>

<br>

<div>
  <%= link_to "Show this worksheet", @worksheet %> |
  <%= link_to "Back to worksheets", worksheets_path %>
</div>

app/views/worksheets/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container mt-5">
  <h1>MRO Worksheets</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Created</th>
        <th>Marine Reported On</th>
        <th>Due Date</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @worksheets.each do |worksheet| %>
        <tr>
          <td><%= worksheet.created_at.strftime("%B %d, %Y %I:%M %p") %></td> <!-- Format created_at -->
          <td><%= "#{worksheet.mro_rank} - #{worksheet.mro_name}" %></td> <!-- MRO Rank and Name -->
          <td><%= worksheet.mmsb_due_date&.strftime("%B %d, %Y") %></td> <!-- Format due date -->
          <td>
            <%= link_to "View", worksheet, class: "btn btn-secondary" %>
            <%= link_to "Edit", edit_worksheet_path(worksheet), class: "btn btn-primary btn-dark" %>
            <%= link_to "Delete", worksheet, class: "btn btn-danger", method: :delete, data: { confirm: "Are you sure?" } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/worksheets/new.html.erb
<div class="container mt-5">
  <h1 class="text-center">New MROW</h1>

  <%= render "form", worksheet: @worksheet %>
</div>

app/views/worksheets/show.html.erb
<div class="container mt-4">
  <p style="color: green"><%= notice %></p>
  <h1><%= @worksheet.mro_rank %> <%= @worksheet.mro_name %> </h1>


  <h2 class="mb-4 mt-5">Worksheet Details</h2>

  <% if notice %>
    <div class="alert alert-success">
      <%= notice %>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-12">
      <h3>Marine Reported On (MRO)</h3>
    </div>

    <div class="col-md-3">
      <strong>Rank:</strong> <%= @worksheet.mro_rank %>
    </div>
    <div class="col-md-5">
      <strong>Name:</strong> <%= @worksheet.mro_name %>
    </div>
    <div class="col-md-4">
      <strong>Billet:</strong> <%= @worksheet.mro_billet %>
    </div>

    <div class="col-md-3">
      <strong>Unit:</strong> <%= @worksheet.mro_unit %>
    </div>
    <div class="col-md-5">
      <strong>Component/Status:</strong> <%= @worksheet.mro_component %> / <%= @worksheet.mro_status %>
    </div>
    <div class="col-md-4">
      <strong>Reporting Occasion:</strong> <%= @worksheet.reporting_occasion %>
    </div>

    <div class="mt-2">
      <div class="col-md-8">
        <strong>Reporting Period:</strong> <%= @worksheet.from_date.strftime("%B %d, %Y") %> through <%= @worksheet.to_date.strftime("%B %d, %Y") %>
      </div>

      <div class="col-md-4">
        <strong>MMSB Due Date:</strong> <%= @worksheet.mmsb_due_date.strftime("%B %d, %Y") %>
      </div>
    </div>

    <div class="mt-2">
      <div class="col-md-12">
        <strong>Reporting Senior (RS):</strong> <%= @worksheet.rs_rank %> <%= @worksheet.rs_name %> (<%= @worksheet.rs_billet %>)
      </div>

      <div class="col-md-12">
        <strong>Reviewing Officer (RO):</strong> <%= @worksheet.ro_rank %> <%= @worksheet.ro_name %> (<%= @worksheet.ro_billet %>)
      </div>
    </div>

    <div class="col-md-12 mt-4">
      <h3>Education and Experience</h3>
      <h4>Schools</h4>
      <strong>Career-Level School (EWS): </strong><%= Education::EDUCATION_STATUS[@worksheet.education.ews.to_sym] %><br>
      <strong>Intermediate-Level School (C&S): </strong><%= Education::EDUCATION_STATUS[@worksheet.education.cns.to_sym] %><br>
      <strong>Top-Level School (War College): </strong><%= Education::EDUCATION_STATUS[@worksheet.education.war_college.to_sym] %><br>
      <strong>Graduate Degree Program (SEP/ADP): </strong><%= Education::EDUCATION_STATUS[@worksheet.education.graduate_degree.to_sym] %><br>
      <strong>Graduate/Adv Degree (Self-Study): </strong><%= Education::EDUCATION_STATUS[@worksheet.education.self_study.to_sym] %><br>
      <strong>JPME Phase I: </strong><%= Education::EDUCATION_STATUS[@worksheet.education.jpm_phase_i.to_sym] %><br>
      <strong>JPME Phase II: </strong><%= Education::EDUCATION_STATUS[@worksheet.education.jpm_phase_ii.to_sym] %><br>
      <strong>[Other school, if applicable]: </strong><%= Education::EDUCATION_STATUS[@worksheet.education.other.to_sym] %><br>
    </div>

    <!-- Recommendations Section -->
    <div class="col-md-12 mt-4">
      <h3>Recommendations</h3>
    </div>
    <div class="col-md-12">
      <strong>Commendatory Fitness Report:</strong> <%= @worksheet.commendatory ? 'Yes' : 'No' %>
    </div>
    <div class="col-md-12">
      <strong>Commendatory Description:</strong> <%= @worksheet.commendatory_description.present? ? @worksheet.commendatory_description : 'N/A' %>
    </div>
    <div class="col-md-12">
      <strong>Recommended Comments:</strong> <%= @worksheet.recommended_comments.present? ? @worksheet.recommended_comments : 'N/A' %>
    </div>
    <div class="col-md-12">
      <strong>Amplifying Information:</strong> <%= @worksheet.amplifying_information.present? ? @worksheet.amplifying_information : 'N/A' %>
    </div>
    <div class="col-md-12">
      <strong>Recommended Comparative Assessment:</strong> <%= @worksheet.recommended_comparative_assessment.present? ? @worksheet.recommended_comparative_assessment : 'N/A' %>
    </div>

    <!-- Action Buttons -->
    <div class="form-group text-center mt-5">
      <%= link_to 'Edit', edit_worksheet_path(@worksheet), class: 'btn btn-primary btn-dark' %>
      <%= link_to 'Back to List', worksheets_path, class: 'btn btn-secondary ml-3' %>
    </div>
  </div>
</div>